### ISSUE TITLE
TypeError: Cannot read property 'stdout' of undefined

### ISSUE THREAD

**Issue by ghost** [netcell/netify#1]
```
Ping to google.com with notification
Use -silent or -s option to stop notification.
/home/mahpah/npm-packages/lib/node_modules/netify/app.js:46
ls.stdout.on('data', function (data) {
  ^

TypeError: Cannot read property 'stdout' of undefined
    at Object.<anonymous> (/home/mahpah/npm-packages/lib/node_modules/netify/app.js:46:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

```
node -v
v4.2.1

npm -v
3.3.10

uname -a                
Linux #### 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by thanhdeptrai** [comment]
I'm sorry, we have not support this app on Linux yet. 

Thank you for your feedback! 

If you want to contribute and/or support us on building Linux version, we'll be really grateful!
